import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import ButtonPrimary from "../components/ButtonPrimary";
import Box from "../components/design-system/Box";
import Header from "../components/header/Header";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
      </main>
    </div>
  );
};

export default Home;
